{% set name = "Hapi" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/Hapi/archive/refs/tags/{{version}}.tar.gz
  sha256: 869ce8242e314fd3b5496d07369ac82a154a226da381300f355350149bd0cfa0


build:
  noarch: python

  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}

  script: "{{ PYTHON }} -m pip install . -vv"

requirements:

  host:
    - python
    - pip
  run:
    - pip >=21.3.1
    - numpy >=1.21.2,<1.22.4
    - gdal >=3.3.3,<3.4.3
    - affine >=2.3.0
    - fiona >=1.8.20
    - proj >=0.2.0
    - pyproj >=3.2.1,<=3.3.0
    - pandas >=1.3.2,<1.4.2
    - geopandas >=0.10.2
    - matplotlib >=3.4.2,<3.6.0
    - python >=3.7.1,<3.10
    - scipy >=1.7.0,<1.8.1
    - shapely >=1.8.0
    - statsmodels >=0.12.2,<0.14.0
    - rasterio >=1.2.10
    - rasterstats >=0.16.0
    - oasis >=0.1.3
    - netCDF4 >=1.5.5,<1.5.9
    - scikit-learn >=0.24.2,<1.0.2
    - scikit-image >=0.18.3
    - ecmwf-api-client >=1.6.1
    - joblib >=1.1.0
    - geopy >=2.2.0
    - pytest >=6.2.5
    - pytest-cov >=2.12.1
    - loguru >=0.5.3
    - geoplot >=0.5.1

test:
  imports:
    - Hapi
  commands:
    - Hapi --help
    - pytest
  requires:
    - pytest
  source_files:
    - tests/
about:
  home: https://github.com/MAfarrag/HAPI
  license: MIT
  summary: 'Distributed Hydrological model'
  description: |
    This module builds Distributed Hydrological model.
  dev_url: https://github.com/MAfarrag/HAPI
  doc_url: https://github.com/MAfarrag/HAPI
  doc_source_url: https://github.com/MAfarrag/HAPI/master/README.md
