channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - numpy >=1.23.5
  - pip >=22.3.1
  - gdal >=3.5.3
  - pandas >=1.4.4
  - geopandas >=0.12.2
  - matplotlib >=3.5.3
  - scipy >=1.9.1
  - statsmodels >=0.13.2
  - rasterio >=1.3.2
  - rasterstats >=0.17.0
  - Fiona >=1.8.21
  - geostatista >=0.1.5
  - statista >=0.1.7
  - pyramids >=0.2.11
  - earth2observe >=0.1.7
  - Oasis >=1.0.2
  - digitalearth >=0.1.10
  - joblib >=1.2.0
  - loguru >=0.6.0
  - requests >=2.28.1
  - pytest >=7.2.0
  - pytest-cov ==4.0.0
