channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - numpy >=1.24.1
  - hpc >=0.1.0
  - pip >=22.3.1
  - PyYAML >=0.6.0
  - pathlib >=1.0.1
  - gdal >=3.5.3
  - pandas >=1.4.4
  - geopandas >=0.12.2
  - matplotlib >=3.6.3
  - scipy >=1.9.1
  - statsmodels >=0.13.2
  - rasterio >=1.3.2
  - rasterstats >=0.17.0
#  - statista >=0.3.0
  - pyramids >=0.4.0
  - Oasis >=1.0.2
  - cleopatra >=0.2.7
  - digitalearth >=0.1.11
  - serapeum_utils >=0.1.1
  - joblib >=1.2.0
  - loguru >=0.6.0
  - requests >=2.28.1
  - pytest
  - pytest-cov
