channels:
  - conda-forge
dependencies:
  - python >=3.7.1,<3.10
  - pip >=21.3.1
  - matplotlib >=3.4.2,<3.6.0
  - pandas >=1.3.2,<1.4.3
  - geopandas >=0.10.2
  - gdal >=3.3.3,<3.5.1
  - oasis >=1.0.2
  - pyramids >= 0.2.0
  - statsmodels >=0.14.0
  - scipy >=1.7.0,<1.8.2
  - rasterstats >=0.16.0
  - pip:
      - digitalearth >= 0.1.0
      - loguru >=0.5.3
#    - ffmpeg-python
