channels:
  - conda-forge
dependencies:
  - numpy >=2.1.3
  - pip >=24.3.1
  - pyramids >=0.6.0
  - PyYAML >=6.0.2
  - gdal >=3.10.0
  - pandas >=2.2.3
  - geopandas >=1.0.1
  - cleopatra >=0.4.0
  - matplotlib >=3.7.2
  - statista >=0.6.0
  - scipy >=1.11.4
  - serapeum_utils >=0.2.0
  - loguru >=0.7.2
  - requests >=2.31.0
  - Oasis >=1.0.3