channels:
  - conda-forge
dependencies:
  - python >=3.11
  - numpy >=1.25.2
  - pip >=23.3.1
  - pyramids >=0.5.4
  - PyYAML >=6.0.1
  - gdal >=3.7.0
  - pandas >=2.1.0
  - geopandas >=0.14.1
  - cleopatra >=0.4.0
  - matplotlib >=3.7.2
  - statista >=0.5.0
  - scipy >=1.11.4
  - serapeum_utils >=0.2.0
  - loguru >=0.7.2
  - joblib >=1.3.2
  - pathlib >=1.0.1
  - pytest >=7.4.3
  - pytest-cov >=4.1.0
  - requests >=2.31.0
  - Oasis >=1.0.2
