channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.12
  - pip >=22.2.2
  - matplotlib >=3.5.3
  - pandas >=1.3.2,<1.4.3
  - geopandas >=0.10.2
  - gdal >=3.3.3,<3.5.1
  - oasis >=1.0.2
  - pyramids >= 0.2.1
  - statsmodels >=0.13.0
  - scipy >=1.7.0,<1.9.1
  - rasterstats >=0.16.0
  - pip:
      - digitalearth >= 0.1.0
      - cleopatra >=0.2.0
      - statista >=0.1.3
      - loguru >=0.6.0
      - requests
#    - ffmpeg-python
