channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.12
  - pip >=22.2.2
  - numpy >=1.23.3
  - loguru >=0.6.0
  - matplotlib >=3.5.3
  - pandas >=1.4.4
  - geopandas >=0.11.1
  - gdal >=3.4.3
  - rasterio >=1.3.2
  - rasterstats >=0.17.0
  - fiona >=1.8.21
  - scipy >=1.9.1
  - statsmodels >=0.13.2
  - pyramids >=0.2.4
  - digitalearth >=0.1.4
  - oasis >=1.0.2
  - pip:
      - loguru >=0.6.0
      - cleopatra >=0.2.2
      - statista >=0.1.5
      - requests
#    - ffmpeg-python
