site_name: Hapi
site_description: The documentation of Hapi Hydrological Model
site_author: Mostafa Farrag

repo_url: https://github.com/MAfarrag/Hapi
edit_url: ""

theme:
    name: readthedocs

nav:
    - Home: index.md
    - Available Models:
        - HBV Bergström 1992: HBV.md
        - Muskingum Routing: Muskingum.md
    - Inputs:
        - Meteorological Inputs: Meteo_Inputs.md
        - GIS Inputs: GIS_inputs.md
        - Parameters: Parameters.md
    - Tutorial:
        - Build Distributed Model: build_model.md
        #- Inputs: CreateInputs.md
        - Lumped Hydrological Model: Lumped_HBV.md
        - Sensitivity Analysis: Sensitivity_Analysis.md
    - GIS: GIS.md
    - License: license.md
