[tool.poetry]
name = "hapi"
version = "1.0.5"
description = "Hydrological and Hydrodynamic modelling tool"
authors = ["Mostafa Farrag <moah.farag@gmail.com>"]

[[tool.poetry.source]]
name = "my-custom-repo"  # This name will be used in the configuration to retreive the proper credentials
url = "https://my.customrepo.com/simple/"  # URL used to download your packages from

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
pandas = "<=1.3.2,<1.3.4"
numpy = ">=1.21.2,<1.21.4"
matplotlib = "=>3.4.2,<3.4.3"
scipy = ">=1.7.0,<1.7.2"
statsmodels = ">=0.12.2,<0.13.0"
netCDF4 = ">=1.5.5,<1.5.8"
scikit-learn = ">=0.24.2,<1.0.1"
scikit-image = "^0.18.3"
joblib = "^1.1.0"
ecmwf-api-client = "^1.6.1"
pyproj = "^3.2.1"
proj = "^0.2.0"
Shapely = "^1.8.0"
gdal = "^3.3.3"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
