name: hapi

channels:
  - conda-forge
dependencies:
  - python
  - pip
  - matplotlib
  - gdal
  - proj
  - affine
  - fiona
  - pandas
  - geopandas
  - scipy
  - shapely
  - statsmodels
  - rasterio
  - rasterstats
  - oasis
  - netCDF4
  - scikit-learn
  - scikit-image
  - ecmwf-api-client
  - joblib
  - hapi
  - pip:
    - numpy
    - pyproj
    - ffmpeg-python
#    - hapi-nile
    - git+https://github.com/MAfarrag/HAPI.git
